### ISSUE TITLE
--include doesn't seem to work

### ISSUE THREAD

**Issue by mausch** [machine/machine.specifications.runner.console#2]
If I create a new project with this trivial spec:

```C#
using Machine.Specifications;

public class when_foo
{
    public It should_do_something = () => { };
}
```

When I try to run with explicitly with `-i` (to avoid running any other specs), the console runner doesn't seem to find any tests.

Concretely, I install Machine.Specifications.Runner.Console from NuGet and run this on the command-line:

```
> packages\Machine.Specifications.Runner.Console.0.9.0\tools\mspec-clr4 -i "when_foo" mspecresharpertest\bin\debug\mspecresharpertest.dll

Specs in mspecresharpertest:

Contexts: 0, Specifications: 0, Time: 0.09 seconds
```

Instead of "when_foo" I've also tried "should_do_something", "when foo", "when_foo.should_do_something" before giving up.

Is there any particular format or way to get the console runner to run only the defined specs?

Thanks.

**Comment by agross** [comment]
You need to define TagsAttribute for the context. You can then use the tag to include or exclude contexts from the test run. 




Alex
-- 
Alexander Groß
Tiny phone, tiny mail

**Comment by mausch** [comment]
Thanks. Is there any other way to filter by "when_foo" / "should_do_something", i.e. without having to define a TagsAttribute?

**Comment by agross** [comment]
No, there isn't. 




Alex
-- 
Alexander Groß
Tiny phone, tiny mail

**Comment by mausch** [comment]
Thanks! Follow-up feature suggestion: https://github.com/machine/machine.specifications.runner.console/issues/3
