### ISSUE TITLE
System.AppDomainUnloadedException is printed without Stack-Trace. Runner terminates with exception.

### ISSUE THREAD

**Issue by BrunoJuchli** [machine/machine.specifications.runner.console#4]
I have some assembly which is spec-tested where sometimes (often) a AppDomainUnloadedException occurs (outside of mspec delegates). It's most likely caused by a rogue thread/task which was not `await`-ed in a spec-test (usually `Because`or `Cleanup`).
Now either my spec test is wrong (not waiting for all work to finish) or my implementation is defective. Therefore i would like to know the origin of the exception.
However, the only text printed to the console is:

>» should connect phone call sender with default microphone

>Unhandled Exception: System.AppDomainUnloadedException: Attempted to access an unloaded AppDomain.

> Contexts: 47, Specifications: 151, Time: 19.72 seconds

**So the stack trace is missing.**

I didn't find the handler which is printing the message at first glance. I'd thought it might be a `AppDomain.UnhandledException +=` handler, but coulnd't find any.

Also note, that in case this error happened the old 0.8 runner would not correctly write the xml report. The file would be there, but it would be empty. The runner executable would terminate in normal fasion. Since my build script parses the xml report to see if there are any errors, my build script failed. 

Now, with the new 0.9 runner, if i enable the "--xml" output the runner often terminates with an exception (Debug / Close Program dialog pops up).
(Note: when i attach the debugger the runner terminates after the debugger has attached - i can't start debugging).

Furthermore i have failed to create a repro yet. I've tried several things unsuccessfully. With our assembly we're using commercial 3rd party libs which i cannot make available to you. It might be related to these 3rd part libs (sadly enough they are of low quality and i think they deal with unmanaged threads.. and they do cleanup / disposal correctly since there's still threads running once all of their stuff is disposed/closed...).

**Comment by agross** [comment]
I never had the same error with my code or in specs. Just to try, can you run the same code with xunit or NUnit and see what it prints? This might help you pinpoint the problem.

**Comment by BrunoJuchli** [comment]
I'll try it on monday.

Due to a bug in a WPF Control finalizer - which we instantiated in a UI test for Binding tests - i've had a similar error (also a `AppDomainUnloadedException`)  in NUnit before.

That bug i've fixed, however ;-)

**Comment by BrunoJuchli** [comment]
I have thought about testing with NUnit, but due to lack of information (exact stacktrace) it's hard to pinpoint the issue to a specific test. I'd have to re-write about 80 Spec tests, seems a bit excessive, doesn't it?

**Comment by BrunoJuchli** [comment]
I suspect [`ExceptionReporter.cs`](https://github.com/machine/machine.specifications.runner.console/blob/9902c3a5cce7760f2b879e0714a51b8617b2527d/Machine.Specifications.ConsoleRunner/ExceptionReporter.cs) is to blame.

**Comment by danielmarbach** [comment]
@BrunoJuchli hotfix-0.9.2

**Comment by BrunoJuchli** [comment]
@danielmarbach 
Do you really want to go from 0.9.0 to 0.9.2 straight? Because there's no 0.9.1 for runner.console yet.

**Comment by BrunoJuchli** [comment]
So as it turns out, the message being printed in my case is printed by the .net framework, not by MSpec's code. The Stacktrace is not printed because there isn't any. Go figure. Really helpful to fix issues oO.

Anyway i think my PR still makes sense, it just doesn't help with my issue :(

**Comment by danielmarbach** [comment]
Your right. I was looking at MSpec and not at the console version. Go for 0.9.1
