### ISSUE TITLE
GitFlowVersionTask dependency is buggy and outdated

### ISSUE THREAD

**Issue by BrunoJuchli** [machine/machine.specifications.runner.console#5]
GitFlowVersionTask produces build errors on fork`s branches (see below).

GitFlowVersionTask has been deprecated and was replaced by [GitVersionTask](https://www.nuget.org/packages/GitVersionTask/).

> Error  1   Error occurred: System.NullReferenceException: Object reference not set to an instance of an object.
>    at GitFlowVersion.OptionallyTaggedBranchVersionFinderBase.NumberOfCommitsInBranchNotKnownFromBaseBranch(IRepository repo, Branch branch, BranchType branchType, String baseBranchName) in y:\BuildAgent\work\5e0d79a4e3943b17\GitFlowVersion\BranchFinders\OptionallyTaggedBranchVersionFinderBase.cs:line 132
>    at GitFlowVersion.OptionallyTaggedBranchVersionFinderBase.FindVersion(IRepository repo, Branch branch, Commit commit, BranchType branchType, String baseBranchName) in y:\BuildAgent\work\5e0d79a4e3943b17\GitFlowVersion\BranchFinders\OptionallyTaggedBranchVersionFinderBase.cs:line 17
>    at GitFlowVersion.HotfixVersionFinder.FindVersion() in y:\BuildAgent\work\5e0d79a4e3943b17\GitFlowVersion\BranchFinders\HotfixVersionFinder.cs:line 13
>    at GitFlowVersion.GitFlowVersionFinder.FindVersion() in y:\BuildAgent\work\5e0d79a4e3943b17\GitFlowVersion\GitFlowVersionFinder.cs:line 28
>    at GitFlowVersion.VersionForRepositoryFinder.GetVersion(Repository repository) in y:\BuildAgent\work\5e0d79a4e3943b17\GitFlowVersion\VersionForDirectoryFinder.cs:line 17
>    at GitFlowVersion.VersionCache.GetVersion(String gitDirectory) in y:\BuildAgent\work\5e0d79a4e3943b17\GitFlowVersion\VersionCache.cs:line 39
>    at GitFlowVersionTask.UpdateAssemblyInfo.InnerExecute() in y:\BuildAgent\work\5e0d79a4e3943b17\GitFlowVersionTask\UpdateAssemblyInfo.cs:line 87
>    at GitFlowVersionTask.UpdateAssemblyInfo.Execute() in y:\BuildAgent\work\5e0d79a4e3943b17\GitFlowVersionTask\UpdateAssemblyInfo.cs:line 43   Example.Issue157-Fail

**Comment by ivanz** [comment]
Migrated away from TeamCity to AppVeyor build and dropped rake+gitflow tasks. Release and versioning is driven from "vX.Y.Z" tags now.
