### ISSUE TITLE
How to specify test settings via command line?

### ISSUE THREAD

**Issue by KevivL** [machine/machine.specifications.runner.console#9]
Is there any option to specify the app.Config or any specific settings/file for the tests to use via command line?

This is distinct from which tests/assembles to run, but instead some settings i wish to inject into the tests themselves.

**Comment by agross** [comment]
Mspec only uses the dll.config file for the respective test assembly.  



Alex
-- 
Alexander Groß
Tiny phone, tiny mail

**Comment by KevivL** [comment]
Ah. Yes saw the examples of that. So varying the settings will require XML
black magic pre-test... Oh well :) was hoping to specify the file to avoid
that. Thanks for the quick reply.
